version: '3'
services:
   jenkins:
      container_name: jenkins
      image: jenkins/jenkins:jdk17
      ports:
        - "8080:8080"
        - "50000:50000"
      volumes:
        - jenkins_home:/var/jenkins_home
      environment:
        - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      networks:
        - jenkins-net
      restart: unless-stopped
volumes:
   jenkins_home:
networks:
   jenkins-net: